services:
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://leaderboard_owner:XKxWby7PDM5R@ep-fancy-mode-a2wxm1lh.eu-central-1.aws.neon.tech/leaderboard?sslmode=require
