name: Python Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy pylint isort bandit
        working-directory: ./backend
      - name: Run linters
        run: |
          black --check .
          flake8
          mypy . --explicit-package-bases
          pylint .
          isort --check-only .
          bandit -r .
        working-directory: ./backend
